Description: >
  Tushar Khachane 
  Capstone project for Cloud DevOps Engineering Nanodegree
Parameters:
  EnvironmentName:
    Description: An Environment name that will be prefixed to resources
    Type: String
    Default: Capstone-Udacity
  
Resources:
  CapstoneEKS:
    Type: AWS::EKS::Cluster
    Properties:
      RoleArn: !ImportValue 
        "Fn::Sub": "${EnvironmentName}-IAM-Role"
      ResourcesVpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub "${EnvironmentName}-Security-Group"
        SubnetIds:
          Fn::Split:
            - ","
            - Fn::ImportValue:
                Fn::Sub: ${EnvironmentName}-PUB-SUBNET
          
Outputs:
  Eksarn:
    Description: The EKS id.
    Value: !GetAtt CapstoneEKS.Arn
    Export:
      Name: !Sub ${EnvironmentName}-EKS-Cluster-ARN
  EksEndpoint:
    Description: The EKS enpoint url
    Value: !GetAtt CapstoneEKS.Endpoint
    Export:
      Name: !Sub ${EnvironmentName}-EKS-URL
  EksId:
    Description: The EKS id.
    Value: !Ref CapstoneEKS
    Export:
      Name: !Sub ${EnvironmentName}-EKS
