Description: >
  Tushar Khachane 
  Capstone project for Cloud DevOps Engineering Nanodegree
Parameters:
  EnvironmentName:
    Description: An Environment name that will be prefixed to resources
    Type: String
    Default: Capstone-Udacity

  ImageID:
    Description: An image ID for EC2 Instance
    Type: String
    Default: ami-09e67e426f25ce0d7

  DesiredInstances:
    Description: How many instances should be created.
    Type: Number
    Default: 2

  MinimumSize:
    Description: Minimum number of web application servers
    Type: Number
    Default: 1

  MaximumSize:
    Description: Maximum number of web application servers
    Type: Number
    Default: 3

Resources:
  NodeInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - "capstone-iam-role-udacity-EKSRole-1DZMAADK34CZD"

  EKSNodegroup:
    Type: 'AWS::EKS::Nodegroup'
    Properties:
      ClusterName: prod
      NodeRole: !ImportValue 
        "Fn::Sub": "${EnvironmentName}-IAM-Role"
      ScalingConfig:
        MinSize: !Ref MinimunSize
        DesiredSize: !Ref DesiredInstances
        MaxSize: !Ref MaximumSize
      Subnets:
        Fn::Split:
          - ","
          - Fn::ImportValue:
              Fn::Sub: ${EnvironmentName}-PUB-SUBNET 
  
Outputs:
  NodesSecurityGroup:
    Description: The security group for the nodes.
    Value: !Ref NodesSG
    Export:
      Name: !Sub ${EnvironmentName}-NSG