Description: >
  Tushar Khachane 
  Capstone project for Cloud DevOps Engineering Nanodegree
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: Capstone-Udacity
  EKSUserName:
    Type: String
    Default: capstone
  EKSRoleName:
    Type: String
    Default: capstone

Resources:

  EKSAssumeRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: EKSAssumeRolePolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Resource: !GetAtt EKSAdminRole.Arn
      Users: 
        - !Ref EKSAdminUser

  EKSAdminUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref EKSUserName
        
  EKSAdminRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Ref EKSRoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !GetAtt EKSAdminUser.Arn
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
      Path: /
  
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref InstanceRole

Outputs:
  EKSAdminUserARN:
    Value: !GetAtt EKSAdminUser.Arn
    Description: EKS Admin User Arn
    Export:
      Name: !Sub ${EnvironmentName}-Admin-User
  EKSAdminRoleARN:
    Value: !GetAtt EKSAdminRole.Arn
    Description: EKS Admin Role Arn
    Export:
      Name: !Sub ${EnvironmentName}-IAM-Role
  InstanceProfile:
    Description: The node instance profile
    Value: !GetAtt InstanceProfile.Arn
    Export:
      Name: !Sub ${EnvironmentName}-Instance-Profile