apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: capstone
  region: us-east-1
nodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 2
    privateNetworking: true
vpc:
  subnets:
    private:
      us-east-1a:
        id: "subnet-0f9db06af54e49f2e"
      us-east-1b:
        id: "subnet-0c261b9f541593789"
  clusterEndpoints:
    publicAccess:  true
    privateAccess: true
