apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: capstone
  region: us-east-1
nodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 2
vpc:
  subnets:
    public:
      us-east-1a:
        id: "subnet-0fabb4fa2f6f02891"
      us-east-1b:
        id: "subnet-0a4f9a2462d704a59"
  clusterEndpoints:
    publicAccess:  true
    privateAccess: true