apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: capstone
        image: tushar887/capstone:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: default-port