apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  labels:
    app: capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: capstone
        image: 671761574982.dkr.ecr.us-east-1.amazonaws.com/capstone
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-svc
spec:
  selector:
    app: capstone
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer