version: 2.1

executors:
  node:
  python:
    docker:
      - image: python:3.7.3-stretch
      
jobs:
  install_dependency:
    executor: python
    working_directory: ~/Capstone-Udacity
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv capstone
            . capstone/bin/activate
            
            #Install requirements to run application using Makefile
            make install
      - persist_to_workspace:
         root: .
         paths:
           -  ~/Capstone-Udacity
      
  linting:
    executor: python
    working_directory: ~/Capstone-Udacity
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Liniting Python code and Dockerfile
          command: |
            ls -alrth
            cd Capstone-Udacity
            ls -larth | grep capstone/bin/
            #Install hadolint to lint Dockerfile
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                chmod +x /bin/hadolint
            make lint
           
          
workflows:
  version: 2
  Capstone:
    jobs:
      - install_dependency
      - linting:
          requires:
            - install_dependency