version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

executors:
  node:
  python:
    docker:
      - image: python:3.7.3-stretch
  docker-image:
    docker:
      - image: docker:17.05.0-ce-git
      
jobs:
  install_dependency:
    executor: python
    working_directory: ~/Capstone-Udacity
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv capstone
            . capstone/bin/activate
            
            #Install requirements to run application using Makefile
            make install
      - persist_to_workspace:
         root: .
         paths:
           -  .
      
  linting:
    executor: python
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Liniting Python code and Dockerfile
          command: |
            . capstone/bin/activate
            #Install hadolint to lint Dockerfile
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                chmod +x /bin/hadolint
            make install
            make lint
           
  build_docker:
    executor: docker-image
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker
#      - run:
##          name: Install Docker
#          command: |
#            sudo curl -L -o /usr/bin/docker 'http://s3-external-1.amazonaws.com/circle-downloads/docker-1.8.2-circleci'
#            sudo chmod 0755 /usr/bin/docker
#            docker --version
      - run:
          name: Building Docker Container
          command: |
           make setup
            . capstone/bin/activate
            pip install docker
            docker --version
            TAG=0.1.$CIRCLE_BUILD_NUM
            #docker rm app
            docker build -t app:$TAG .
            docker images
          
workflows:
  version: 2
  Capstone:
    jobs:
#      - install_dependency
#      - linting:
#          requires:
#            - install_dependency
      - build_docker #:
 #         requires:
#            - install_dependency