version: 2.1

executors:
  node:
  python:
    docker:
      - image: python:3.7.3-stretch
      
jobs:
  install_dependency:
    executor: python
    working_directory: ~/Capstone-Udacity
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1--dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      
      - run:
          command: |
            python3 -m venv capstone
            . capstone/bin/activate
            
            #Install requirements to run application using Makefile
            make install
            
            #Install hadolint to lint Dockerfile
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                chmod +x /bin/hadolint
      
      - save_cache:
          paths:
            - ./capstone
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          
          
workflows:
  version: 2
  Capstone:
    jobs:
      - install_dependency