version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

executors:
  node:
  python:
    docker:
      - image: python:3.7.3-stretch
  docker-image:
    docker:
      - image: docker:17.05.0-ce-git
  aws:
    docker:
      - image: amazon/aws-cli
  ubuntu:
    docker:
      - image: cimg/base:2021.04

      
jobs:
  install_dependency:
    executor: python
    working_directory: ~/Capstone-Udacity
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv capstone
            . capstone/bin/activate
            
            #Install requirements to run application using Makefile
            make install
      - persist_to_workspace:
         root: .
         paths:
           -  .
      
  linting:
    executor: python
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Liniting Python code and Dockerfile
          command: |
            . capstone/bin/activate
            #Install hadolint to lint Dockerfile
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                chmod +x /bin/hadolint
            make install
            make lint
           
  build_docker:
    executor: docker-image
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Building Docker Image and Pushing to DockerHub
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            dockerpath=tushar887/capstone
            docker build -t capstone:$TAG .
            docker images
            docker tag capstone:$TAG $dockerpath:$TAG
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASS"
            docker push $dockerpath:$TAG
      
  connect_to_cluster:
    executor: ubuntu
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command:  |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
            echo "$(<kubectl.sha256) kubectl" | sha256sum --check
            sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
            kubectl version --client
            sudo apt-get install docker-ce docker-ce-cli containerd.io
            docker --version
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            aws --version
      - run:
          name: Connecting cluster and worker node
          working_directory: ./.circleci/cloudformation/deployment
          command: |
            aws eks update-kubeconfig --name prod
            kubectl apply -f app.yml
            kubectl wait --for=condition=available --timeout=300s --all deployments        
workflows:
  version: 2
  Capstone:
    jobs:
#      - install_dependency
#      - linting:
#          requires:
#            - install_dependency
#      - build_docker
#      - create_infrastructure
       - connect_to_cluster